defaults:
  rmf_level: L1
  map_frame: map
  robot_frame: base_link
  command_topic: /command
  state_topic: /state
  nav2_action: /navigate_to_pose
  battery_percent_topic: /battery/percent
  emergency_topic: /emergency
  follow_command_topic: /follow_command
  follow_event_topic: /follow_event
  assume_full_battery_if_missing: true
  allow_blocked_retry: true
  nav2_server_timeout: 2.0
  goal_acceptance_timeout: 5.0
  state_publish_frequency: 10.0

robots:
  pinky1: {}
  pinky2: {}
