# RMF domain 31 <-> jetcobot1 local domain 34
# RMF /jetcobot1/command -> jetcobot1 /command
# jetcobot1 /state -> RMF /jetcobot1/state
name: jetcobot1_domain_bridge
from_domain: 30
to_domain: 33

topics:
  jetcobot1/command:
    type: jetcobot_msgs/msg/ArmCommand
    remap: command

  state:
    type: jetcobot_msgs/msg/ArmState
    remap: jetcobot1/state
    reversed: true
