fleet_name: pinky
task_api_request_topic: task_api_requests
task_api_response_topic: task_api_responses
default_wait_seconds: 20
warehouse_waypoint: warehouse
return_map: L1
return_pose: [0.15874, 0.43924, 0.0]
